/*   lunedì 26 ottobre 2015 7.07.53   User: sa   Server: VMXP-SERVER   Database: Sagra   Application: MS SQLEM - Data Tools*/BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.StatoOrdini ADD
	DataFineTimeStamp smalldatetime NULL
GO
DROP INDEX dbo.StatoOrdini.IX_StatoOrdini
GO
CREATE NONCLUSTERED INDEX IX_StatoOrdini ON dbo.StatoOrdini
	(
	Id_Sagra,
	Stato,
	DataFineTimeStamp
	) WITH FILLFACTOR = 90 ON [PRIMARY]
GO
COMMIT
