INSERT INTO ScriptDB([DDLVersion], [ScriptName], [SwVersione], [DataInserimento], [Note])
VALUES(28,'28 - User flgLimitated', '2.5.150', CURRENT_TIMESTAMP, 'Aggiunta flag per gestione utenti tecnici o limitati')
go 


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.Users ADD
	FlgLimitated bit NOT NULL CONSTRAINT DF_Users_FlgLimitated DEFAULT 0
GO
COMMIT
