/*   lunedì 28 agosto 2017 13.16.57   User: sa   Server: VMXP-SERVER   Database: SagraCopia   Application: MS SQLEM - Data Tools*/BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
CREATE TABLE dbo.ScriptDB
	(
	ScriptName varchar(50) NOT NULL,
	SwVersione varchar(20) NOT NULL,
	DataInserimento varchar(20) NOT NULL,
	Note varchar(255) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ScriptDB ADD CONSTRAINT
	PK_ScriptDB PRIMARY KEY CLUSTERED 
	(
	ScriptName
	) ON [PRIMARY]

GO
COMMIT

GRANT  SELECT ,  UPDATE ,  INSERT ,  DELETE  ON [dbo].[ScriptDB]  TO [public]
GO