INSERT INTO ScriptDB([ScriptName], [SwVersione], [DataInserimento], [Note])
VALUES('4_1-TipiStampa-CreateUniqueIndex.sql', 'xx', CURRENT_TIMESTAMP, '')
go

/*   lunedì 28 agosto 2017 13.06.25   User: sa   Server: VMXP-SERVER   Database: SagraCopia   Application: MS SQLEM - Data Tools*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.TipiStampa ADD CONSTRAINT
	PK_TipiStampa PRIMARY KEY CLUSTERED 
	(
	IdStampa
	) ON [PRIMARY]

GO
COMMIT

