INSERT INTO ScriptDB([DDLVersion], [ScriptName], [SwVersione], [DataInserimento], [Note])
VALUES(20,'20 - Categori_ModificaPK.sql', '2.4.114', CURRENT_TIMESTAMP, 'ALLARGO CHIAVE PRIMARIA CON iDSAGRA')
go

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
ALTER TABLE dbo.AnagraficaArticoli
	DROP CONSTRAINT FK_AnagraficaArticoli_Categorie
GO
ALTER TABLE dbo.AnagraficaArticoli
	DROP CONSTRAINT FK_AnagraficaArticoli_Categorie1
GO
ALTER TABLE dbo.Categorie
	DROP CONSTRAINT PK_Categorie
GO
ALTER TABLE dbo.Categorie ADD CONSTRAINT
	PK_Categorie PRIMARY KEY CLUSTERED 
	(
	Id_Sagra,
	IdCategoria
	) ON [PRIMARY]

GO
COMMIT
